### PR TITLE
LICENSE VIEW

### PR DESCRIPTION
**Pull request by nayangupta824**

### CODE REVIEW

**Review by lucasgruwez — COMMENTED** [review]
What on the earth did you change ?? 😕

**Comment by owenvoke** [comment]
He changed absolutely nothing 😛 Just removed a space. Lol. Definitely wants a Hacktoberfest top 😉

**Comment by nayangupta824** [comment]
No not a space ... heading was not showing

**Comment by nayangupta824** [comment]
it was like ##license

**Comment by nayangupta824** [comment]
screenshot from 2016-10-12 16-39-06
check this

**Comment by owenvoke** [comment]
Fair enough. 😄

**Comment by arguiot** [comment]
Hey, If you want the Hacktoberfest T-Shirt, that's completely fine, reopen your pull request, I'll accept it

**Comment by owenvoke** [comment]
Just confirming, I sounded a bit harsh but it wasn't meant to be.

**Comment by nayangupta824** [comment]
No problem @PXgamer

**Pull request closed without merging**
